import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
const errors = [];
page.on("console", (m) => m.type() === "error" && !/Failed to load resource/.test(m.text()) && errors.push(m.text().slice(0, 120)));
page.on("pageerror", (e) => errors.push(String(e).slice(0, 120)));
await page.goto("http://127.0.0.1:3000", { waitUntil: "networkidle", timeout: 45000 });
await page.locator("textarea").first().waitFor({ timeout: 20000 });
await page.waitForTimeout(4000);
const powerBtn = page.locator('button[aria-label*="engine" i]').first();
const label = await powerBtn.textContent().catch(() => "(none)");
const ariaLabel = await powerBtn.getAttribute("aria-label").catch(() => "(none)");
console.log("POWER BUTTON label:", JSON.stringify(label));
console.log("POWER BUTTON aria-label:", JSON.stringify(ariaLabel));
const engineStatus = await fetch("http://127.0.0.1:3000/api/netlify/engine-status").then((r) => r.json());
console.log("ENGINE STATUS from API:", JSON.stringify(engineStatus));
await page.screenshot({ path: "/tmp/smoke-header.png" });
console.log("console/page errors:", errors.length === 0 ? "NONE" : errors.slice(0, 3).join(" | "));
await browser.close();
