-keepclassmembers class com.aether.app.AetherBridge { public *; }
-keepattributes JavascriptInterface
-dontwarn com.google.errorprone.annotations.**
-dontwarn javax.annotation.**
-dontwarn javax.annotation.concurrent.**
-dontwarn org.json.**
